### PR TITLE
Error status

### PR DESCRIPTION
**Pull request by maylam36**

### CODE REVIEW

**Review by maylam36 — COMMENTED** [review]
changes look good

**Review by maylam36 — COMMENTED** [review]
I like it

**Review by maylam36 — COMMENTED** [review]
need to change collection_interval to 'dynamic'
Screenshot 2023-07-25 at 3 30 32 PM

**Review by lammay99 — APPROVED** [review]
I approve this message

**Review by lammay99 — APPROVED** [review]
approved again

**Comment by lammay99** [comment]
more changes?

**Review by lammay99 — APPROVED** [review]
approved x 3

**Review by lammay99 — APPROVED** [review]
test

**Pull request merged**
